### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by alxpettit** [JoaquinTrinanes/nushell-nightly-flake#2]
Would it be feasible to add nightly official plugin builds, pulled at the same time so as to ensure compatibility? (e.g., formats, gstat, net, query, regex)

**Comment by JoaquinTrinanes** [comment]
That would  be nice. I always used the nixpkgs plugins and never found any compatibility issue, but it's just a matter of time until they happen.

I'll try to fit that feature alongside a rework of how (cross)compilation works :)

**Comment by alxpettit** [comment]
Oh, sounds awesome! :D
